### ISSUE TITLE
new papers

### ISSUE THREAD

**Issue by abcdvzz** [zwzhang121/Awesome-of-Long-Tailed-Recognition#2]
https://arxiv.org/abs/2008.03673
https://arxiv.org/abs/2007.12229
https://arxiv.org/abs/2008.03428

**Comment by zwzhang123** [comment]
> https://arxiv.org/abs/2008.03673
> https://arxiv.org/abs/2007.12229
> https://arxiv.org/abs/2008.03428

thanks.

**Comment by abcdvzz** [comment]
Rethinking the Value of Labels for Improving Class-Imbalanced Learning， Arxiv Preprint 2020
