### ISSUE TITLE
About iNaturalist2017/2018

### ISSUE THREAD

**Issue by kxgong** [zwzhang121/Awesome-of-Long-Tailed-Recognition#3]
Thanks for your thorough survey. I am recently researching into Long-Tailed Recognition. And your survey is very helpful.
But I can not download the dataset 'iNaturalist 2017' and 'iNaturalist 2018'. I am wondering whether you can share the datasets if you have, better through Baidu Netdisk. Thanks in advance

**Comment by zwzhang123** [comment]
Hi, the iNaturalist 2018 data set can be download in [https://drive.google.com/file/d/1yi1OO1cOt4LvhWMkV5ExyRzOBqquJMtL/view?usp=sharing]. This is also somebody shared to me, if you download it successfully, welcome to share the URL of the Baidu net disk.

**Comment by kxgong** [comment]
Hi, thanks for your sharing! I am downloading the dataset file. I hope I can download it sucessfully. And when I am done with the downloading, I will try to share the dataset on Baidu Netdisk (with the acknowledgement of your sharing).

**Comment by BinhuiXie** [comment]
> Hi, the iNaturalist 2018 data set can be download in [https://drive.google.com/file/d/1yi1OO1cOt4LvhWMkV5ExyRzOBqquJMtL/view?usp=sharing]. This is also somebody shared to me, if you download it successfully, welcome to share the URL of the Baidu net disk.

Hi, the link is invalid, would you mind to share another link? Thanks~

**Comment by zwzhang123** [comment]
> > Hi, the iNaturalist 2018 data set can be download in [https://drive.google.com/file/d/1yi1OO1cOt4LvhWMkV5ExyRzOBqquJMtL/view?usp=sharing]. This is also somebody shared to me, if you download it successfully, welcome to share the URL of the Baidu net disk.
> 
> Hi, the link is invalid, would you mind to share another link? Thanks~

The download URL is OK!

**Comment by BinhuiXie** [comment]
Thanks so much for your reply!
